# Generated by Django 4.0.5 on 2022-06-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.AddField(
            model_name='band',
            name='title',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
